### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by rohit12043-zz** [dev-harsh1998/android_device_lenovo_a6000#15]
Error while compiling PixelExperience-P for Lenovo A6000

including vendor/qcom/opensource/rcs-service/Android.mk ...
device/lenovo/a6000/camera/QCamera2/HAL/Android.mk: error: camera.msm8916 (SHARED_LIBRARIES android-arm) missing libqdMetaData (SHARED_LIBRARIES android-arm)
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
build/make/core/main.mk:837: error: exiting from previous errors.
22:48:45 ckati failed with: exit status 1

**Comment by rohit12043-zz** [comment]
Why the issue is closed

**Comment by adithya2306** [comment]
@rohit12043 issues section aint a place to report stupid build errors by noob buildbots
